/* eslint-disable react/no-unescaped-entities -- static legal prose; straight quotes are intentional */
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — ModularPlatform",
};

/**
 * Public Privacy Policy page — no auth required.
 * Linked from the registration form's acceptTerms checkbox and the cookie consent banner.
 */
export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-background px-4 py-12">
      <div className="mx-auto max-w-2xl space-y-8">
        <header className="space-y-2">
          <h1 className="text-3xl font-semibold tracking-tight">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground">Last updated: 20 June 2026</p>
        </header>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">1. Who We Are</h2>
          <p className="text-muted-foreground leading-relaxed">
            ModularPlatform is a SaaS platform operated as a data controller under the General
            Data Protection Regulation (GDPR). References to "we", "us", or "our" mean the
            platform operator. If you have questions about this policy, contact us via the
            support channel in your account dashboard.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">2. Data We Collect</h2>
          <p className="text-muted-foreground leading-relaxed">
            We collect data you provide directly (name, email, password hash, display name),
            data generated by your use of the service (audit logs, billing records, notification
            history, files you upload), and, with your consent, analytics data (page views,
            feature usage) and marketing data (click-through records for communications we send).
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">3. Legal Basis for Processing</h2>
          <p className="text-muted-foreground leading-relaxed">
            We process your personal data on the following bases: contract performance (to
            provide the service you signed up for), legal obligation (audit retention, AML),
            legitimate interest (security monitoring, fraud prevention), and consent (analytics,
            marketing, third-party sharing — you can change these at any time in Privacy
            settings).
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">4. How We Use Your Data</h2>
          <p className="text-muted-foreground leading-relaxed">
            Your data is used to operate and improve the platform, to send transactional
            notifications (account activity, billing receipts), to fulfil legal obligations,
            and — with your consent — to analyse usage patterns and to send marketing
            communications. We do not sell your personal data to third parties.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">5. Cookies</h2>
          <p className="text-muted-foreground leading-relaxed">
            We use strictly necessary cookies to maintain your authenticated session (iron-session
            cookie). With your consent we also set analytics cookies to measure how you use the
            platform and marketing cookies to record consent preferences. You can manage your
            cookie choices at any time via the cookie settings link in the footer.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">6. Data Retention</h2>
          <p className="text-muted-foreground leading-relaxed">
            We retain your personal data for as long as your account is active. Audit and
            billing records are retained for the minimum period required by applicable law
            (typically 7–10 years) even after account deletion; personal identifiers in those
            records are anonymised on erasure. All other data is deleted within 30 days of
            account closure.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">7. Your Rights</h2>
          <p className="text-muted-foreground leading-relaxed">
            Under GDPR you have the right to access, rectify, erase, restrict, and port your
            personal data, and to object to processing. You can exercise most rights directly
            in the Privacy settings page. To download all data we hold about you, use the
            "Download my data" button. To permanently delete your account and erase personal
            data, use the "Delete my account" option — this crypto-shreds your encryption key
            so stored data becomes permanently unrecoverable.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">8. Security</h2>
          <p className="text-muted-foreground leading-relaxed">
            Passwords are hashed using Argon2. Sensitive personal data fields are encrypted at
            rest (AES-GCM) under per-subject encryption keys. TLS is enforced in transit.
            Access to personal data is restricted to the data subject and platform
            administrators via role-based permissions and Postgres row-level security.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">9. Third-Party Processors</h2>
          <p className="text-muted-foreground leading-relaxed">
            We use Stripe for payment processing (subject to Stripe's privacy policy). Where
            enabled by your tenant, we may share data with other processors listed in the
            platform settings. We enter into data processing agreements with all sub-processors
            and require them to apply equivalent protections.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold">10. Changes to This Policy</h2>
          <p className="text-muted-foreground leading-relaxed">
            We may update this policy from time to time. Material changes will be communicated
            via the platform or by email before they take effect. The "Last updated" date at
            the top reflects the most recent revision.
          </p>
        </section>

        <footer className="border-t border-border pt-6">
          <Link
            href="/login"
            className="text-sm text-primary underline underline-offset-4"
          >
            ← Back to sign in
          </Link>
        </footer>
      </div>
    </div>
  );
}
